### ISSUE TITLE
kronecker product implementation and difference with torch.kron

### ISSUE THREAD

**Issue by dorost1234** [bayer-science-for-a-better-life/phc-gnn#2]
Hi
I tried to test your kronecker product implementation and compare it with torch implementation, for the matrices of the dimension on the example you provided in https://github.com/bayer-science-for-a-better-life/phc-gnn/issues/1 :

```
def kronecker_product1(a, b):
    siz1 = torch.Size(torch.tensor(a.shape[-2:]) * torch.tensor(b.shape[-2:]))
    res = a.unsqueeze(-1).unsqueeze(-3) * b.unsqueeze(-2).unsqueeze(-4)
    siz0 = res.shape[:-4]
    out = res.reshape(siz0 + siz1)
    return out

def kronecker_product2(a, b):
   return torch.kron(a, b)
```

Now lets test the two versions:
```
a = torch.rand((4, 4, 4))
b = torch.rand((4, 64, 32))
result1 = kronecker_product1(a, b)
print("result 1 ", result1.shape)
result2 = kronecker_product2(a, b)
print("result 2 ", result2.shape)
```

The results are not the same and even dimension-wise they differ:

```
result 1  torch.Size([4, 256, 128])
result 2  torch.Size([16, 256, 128])
```

Could you kindly assist me how I can use the torch.kron implementation and which modifications are needed?  

thanks

**Comment by dorost1234** [comment]
Actually now that the results differs from pytorch implementation, are you sure the implementation you used is correct?

**Comment by tuanle618** [comment]
Hey, the shape for `result2` returned by `torch.kron` is expected, as it computes the (Kronecker) outer product between all dimensions, **not considering** a batchwise-computation. Recall, that in our case, we want to compute the Kronecker product for **each** pair of order-2 tensor along the first phm-dimension. 
That means, if `a` has shape `(4,4,4)` and `b` has shape `(4, 64, 32)` , a "true" batched Kronecker product, computes 4 separate Kronecker products along the first dimension. 
The first Kronecker product considers `a[0, :, :]` and `b[0, :, :]` , returning the first `(256,128)` matrix. The second Kronecker product considers `a[1, :, :]` and `b[1, :, :]`, returning the second `(256,128)` matrix,... and so on until the fourth.

Since the batch-dimension consists of 4 elements, a correct batch-dimension Kronecker product would have shape `(4,256,128)`. To use `torch.kron`, you'd have to loop in order to compute the Kronecker products separately.

That means, following your example with the created tensors `a` and `b` :
```python
results2_looped = torch.stack([torch.kron(ai, bi) for ai, bi in zip(a,b)], dim=0)
d = result1 - results2_looped
print(d.norm())
# tensor(0.)

```

I believe the true results are also stored somehow in `torch.kron` (i.e., `result1` is included in `result2`), but this computation includes unnecessary calculations, which we do not need in our case, or in general, if you consider a batch-wise computation.
We did not use torch.kron in our implementation, as it was not available in `torch=1.7.1`. However, the current `torch.kron` is a bit misleading, if you want to have a true batch-wise Kronecker product computation.

If you are familiar with the einsum-notation, you might look into our kronecker_product einsum function:  https://github.com/bayer-science-for-a-better-life/phc-gnn/blob/e802868bea7b9d1cad15c8227b109a8b4ca2a8e7/phc/hypercomplex/kronecker.py#L35-L48
This should make it clearer. 

I hope this answers your question.

**Comment by dorost1234** [comment]
Hi @tuanle618 
thanks a lot for the great explanations, to my surprise the two methods you mentioned are far faster than kron implementation of pytorch!

**Comment by tuanle618** [comment]
Hey @dorost1234,

Glad to hear that your questions are answered.
I am going to close the issue. Feel free to re-open again, if you have further questions.
